
id = "Glassbeach"
name = "Glass Beach skybox"
description = "Gleach."
version = "1.0.0"
homepage = "https://github.com/JinglBellss/Glassbeach"
author = "Vee"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./WebfishingSampleMod/WebfishingSampleMod.csproj"
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.14"
